### PR TITLE
 add mysql backup script and documentation

### PR DESCRIPTION
**Pull request by jay-meister**
# Ready for review

- adds mysql backup script
- adds documentation
- adds brief description on how to schedule backups on Heroku

#3

### CODE REVIEW

**Comment by naazy** [comment]
Nice one @JMurphyWeb! Looks great 😄 🌈 🐸 :1st_place_medal: 🐒 

One tiny thing is that I don't think people will know that there are my-sql instructions in this repo. I think it would be good to either add your instructions to the main README (clearly distinguishing the my sql part and the postgres part) OR add a link in the readme to the my-sql.md (under a clear my sql header). Thoughts?

**Comment by jay-meister** [comment]
good point @naazy 

I added a small header to the top of the README:
screen shot 2017-06-15 at 09 18 03

**Review by nelsonic — APPROVED** [review]
@JMurphyWeb 👍

**Comment by jay-meister** [comment]
@naazy 👍  / 👎  ?

**Comment by naazy** [comment]
:+1: @JMurphyWeb ⭐️

**Pull request merged**
